<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=home.;Initial Catalog=sdb;Integrated Security=True"
            DeleteCommand="delete from emp where empno=@empno" InsertCommand="insert into emp(empno,empname,empsal)values(@empno,@empname,@empsal)&#13;&#10;"
            ProviderName="System.Data.SqlClient" SelectCommand="select * from emp" UpdateCommand="update emp set empsal=@empsal where empno=@empno">
        </asp:SqlDataSource>
    
    </div>
        <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" AutoGenerateInsertButton="True" CellPadding="4"
            DataKeyNames="empno" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None"
            Height="173px" Style="left: 256px; position: relative; top: 49px" Width="301px">
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="White" />
        </asp:DetailsView>
    </form>
</body>
</html>
